"""HLS synthesis execution and result parsing utilities."""

import subprocess
import time
import xml.etree.ElementTree as ET
from datetime import datetime
from pathlib import Path
from typing import Dict, List

from fpga_specs import U280_SPEC

_TARGET_CLOCK_NS   = 2.5                        # 400 MHz design target

def _get_ops_cflags(project_dir: Path, env: Dict) -> str:
    """Build compiler-flag string for Vitis HLS add_files."""
    ops_install = env.get('OPS_INSTALL_PATH', '')
    flags = [f'-I{project_dir / "hls/device/include/"}', '-DOPS_FPGA']
    if ops_install:
        flags += [
            f'-I{ops_install}/hls/include/device/',
            f'-I{ops_install}/hls/L1/include/',
        ]
    return ' '.join(flags)


def timestamp():
    """Return current timestamp string."""
    return datetime.now().strftime("%H:%M:%S")


def parse_csynth_xml(xml_file: Path) -> Dict:
    """Parse a csynth.xml report and return a partial metrics dict.

                Fields populated (where available in the XML):
                        frequency, timing_slack_ns, initiation_interval,
            bram, dsp, ff, lut

    Raises RuntimeError if the file cannot be parsed.
    """
    metrics: Dict = {
        'frequency': 0.0,
        'timing_slack_ns': None,
        'initiation_interval': 0,
        'bram': 0, 'dsp': 0, 'ff': 0, 'lut': 0,
    }
    try:
        root = ET.parse(str(xml_file)).getroot()

        # --- Timing / frequency ---
        ua = root.find('UserAssignments')
        pe = root.find('PerformanceEstimates')
        if ua is not None and pe is not None:
            target_ns_el   = ua.find('TargetClockPeriod')
            uncert_el      = ua.find('ClockUncertainty')
            est_el         = pe.find('SummaryOfTimingAnalysis/EstimatedClockPeriod')
            if target_ns_el is not None and est_el is not None:
                target_ns      = float(target_ns_el.text)
                estimated_ns   = float(est_el.text)
                uncertainty_ns = float(uncert_el.text) if uncert_el is not None else 0.0
                achievable_ns  = estimated_ns + uncertainty_ns
                metrics['frequency']       = min(1000.0 / achievable_ns, 1000.0 / target_ns)
                metrics['timing_slack_ns'] = target_ns - estimated_ns

        # --- Initiation interval ---
        if pe is not None:
            # --- PipelineII from sub-function loop reports ---
            # Present in pipeline sub-function XMLs (e.g. stencilRun_Pipeline_*);
            # pick the first loop with a valid PipelineII value.
            loop_section = pe.find('SummaryOfLoopLatency')
            if loop_section is not None:
                for loop_el in loop_section:
                    ii_el = loop_el.find('PipelineII')
                    if ii_el is not None and ii_el.text not in (None, 'undef', '-', '?'):
                        try:
                            ii_val = int(ii_el.text)
                            if 0 < ii_val < 10000:
                                metrics['initiation_interval'] = ii_val
                                break
                        except ValueError:
                            pass

        # --- Resource estimates ---
        ae = root.find('AreaEstimates/Resources')
        if ae is not None:
            def _int(tag: str) -> int:
                el = ae.find(tag)
                return int(el.text) if el is not None and el.text else 0
            metrics['bram'] = _int('BRAM_18K')
            metrics['dsp']  = _int('DSP')
            metrics['ff']   = _int('FF')
            metrics['lut']  = _int('LUT')
    except Exception as exc:
        raise RuntimeError(f"Failed to parse csynth XML {xml_file}: {exc}") from exc

    return metrics


def generate_csynth_tcl(
    project_dir: Path,
    kernel_cpp: Path,
    tcl_output: Path,
    part: str,
    clock_period_ns: float,
    cflags: str,
) -> None:
    """Write a Vitis HLS TCL script that runs csynth_design for *kernel_cpp*.

    The resulting project is created inside *project_dir* in a sub-folder
    named ``<kernel_stem>_csynth``.  Reports land under:
      <project_dir>/<kernel_stem>_csynth/solution/syn/report/
    """
    kernel_name = kernel_cpp.stem
    script = f"""\
# Auto-generated by synthesis_runner.py — do not edit by hand.
set project_name {kernel_name}_csynth
open_project -reset $project_name
add_files {{{kernel_cpp}}} -cflags "{cflags}"
set_top {kernel_name}
open_solution -reset solution -flow_target vitis
set_part {{{part}}}
create_clock -period {clock_period_ns} -name default
csynth_design
exit
"""
    tcl_output.write_text(script)


def _parse_csynth_reports(report_dirs: List[Path], thread_id: int = None, label: str = '') -> Dict:
    """Parse CSynthesis reports from *report_dirs*.

        Strategy:
            • For each report directory, parse ``csynth.xml`` and related
                ``*_csynth.xml`` files only.
            • Frequency/slack/latency/resources are sourced from XML.
            • Initiation interval is sourced from sub-function XML ``PipelineII``.

    Returns the same dict structure as ``parse_synthesis_results``.
    """
    metrics: Dict = {
        'frequency': 0.0,
        'latency': 0,
        'initiation_interval': 0,
        'bram': 0, 'dsp': 0, 'ff': 0, 'lut': 0,
        'timing_slack_ns': None,
    }
    _resources_set = False
    _found_report_dir = False

    for rpt_dir in report_dirs:
        if not rpt_dir.exists():
            continue
        _found_report_dir = True

        # --- XML: frequency, slack, latency, resources ---
        xml_file = rpt_dir / 'csynth.xml'
        if not xml_file.exists():
            raise RuntimeError(f"Missing csynth.xml in {rpt_dir}")
        xml_m = parse_csynth_xml(xml_file)
        if xml_m.get('frequency', 0) > 0 and metrics['frequency'] == 0:
            metrics['frequency']       = xml_m['frequency']
            metrics['timing_slack_ns'] = xml_m['timing_slack_ns']
        if not _resources_set:
            for k in ('bram', 'dsp', 'ff', 'lut'):
                metrics[k] = xml_m[k]
            _resources_set = True

        # --- XML files for II (pipeline sub-functions have PipelineII) ---
        if metrics['initiation_interval'] == 0:
            # Scan all XMLs in the report dir looking for one with PipelineII set.
            for xml_f in sorted(rpt_dir.glob('*_csynth.xml')):
                if any(x in xml_f.name.lower() for x in ('datamover', 'axis', 'stream')):
                    continue
                sub = parse_csynth_xml(xml_f)
                if sub.get('initiation_interval', 0) > 0:
                    metrics['initiation_interval'] = sub['initiation_interval']
                    break

    if not _found_report_dir:
        raise RuntimeError("No CSynthesis report directories were found")

    # Ensure II is non-zero when frequency is valid.
    if metrics['frequency'] > 0 and metrics['initiation_interval'] == 0:
        metrics['initiation_interval'] = 1

    if thread_id:
        slack_str   = (f"slack={metrics['timing_slack_ns']:.3f}ns"
                       if metrics['timing_slack_ns'] is not None else "slack=N/A")
        _lbl = f" [{label}]" if label else ''
        print(f"[{timestamp()}] [Thread {thread_id}]{_lbl} Parsed (csynth): "
              f"{metrics['frequency']:.1f} MHz, {slack_str}, "
              f"II={metrics['initiation_interval']}, "
              f"BRAM={metrics['bram']}, DSP={metrics['dsp']}, "
              f"FF={metrics['ff']}, LUT={metrics['lut']}")

    if metrics['frequency'] == 0:
        raise RuntimeError("No valid frequency found in csynth XML reports")
    if metrics['initiation_interval'] == 0:
        raise RuntimeError("No initiation interval found in csynth XML reports")

    return metrics


def run_synthesis_with_progress(
    project_dir: Path,
    config: Dict,
    thread_id: int,
    timeout: int,
    env: Dict,
) -> Dict:
    """Run Vitis HLS C-Synthesis directly (no v++ XO/IP packaging).

    This CSynth-only path skips v++ compilation, RTL synthesis, and IP
    packaging steps that follow CSynthesis — usually ~50 % of the total
    ``v++ --compile`` wall time.

    Workflow
    --------
    1. ``make clean``           — remove stale build artefacts
    2. ``make .generated_hls``  — run the OPS translator for the new config
    3. For each kernel .cpp (excluding datamover/axis/stream infrastructure):
       a. Generate a ``vitis_hls`` TCL script
       b. Run ``vitis_hls -f <script.tcl>``
    4. Parse csynth XML reports for metrics.

    Returns ``synthesis_success=False`` on any failure.
    """
    app   = config.get('app_name', '?')
    vf    = config.get('vector_factor', '?')
    ipf   = config.get('iter_par_factor', '?')
    label = f"{app} p={ipf} V={vf}"

    start_time = time.time()
    deadline   = start_time + timeout

    def _remaining():
        return max(1, deadline - time.time())

    def _run(cmd, desc, cwd=None):
        t = _remaining()
        print(f"[{timestamp()}] [Thread {thread_id}] [{label}] {desc}...")
        proc = subprocess.Popen(
            cmd, cwd=cwd or project_dir,
            stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
            universal_newlines=True, env=env, bufsize=1,
        )
        lines = []
        try:
            stdout, _ = proc.communicate(timeout=t)
            for line in stdout.splitlines():
                line = line.rstrip()
                lines.append(line)
                if ('error' in line.lower()
                        and 'warning' not in line.lower()
                        and '0 errors' not in line.lower()):
                    print(f"[{timestamp()}] [Thread {thread_id}] [{label}] [ERROR] {line}")
        except subprocess.TimeoutExpired:
            proc.kill()
            try:
                stdout, _ = proc.communicate(timeout=5)
                lines.extend(stdout.splitlines() if stdout else [])
            except Exception:
                pass
            raise
        return proc.returncode, lines

    try:
        # 1. Clean
        _run(['make', 'clean'], "Cleaning")

        # 2. Generate HLS sources (OPS translator only — fast)
        ret, out = _run(['make', '.generated_hls'], "Generating HLS sources")
        if ret != 0:
            raise RuntimeError(f"OPS translation failed:\n" + '\n'.join(out[-20:]))

        # 3. Locate kernel source files
        src_dir = project_dir / 'hls' / 'device' / 'src'
        kernel_cpps = [
            f for f in src_dir.glob('*.cpp')
            if not any(x in f.stem.lower() for x in ('datamover', 'axis', 'stream'))
        ]
        if not kernel_cpps:
            raise RuntimeError(f"No kernel.cpp files found in {src_dir}")

        part       = 'xcu280-fsvh2892-2L-e'
        cflags     = _get_ops_cflags(project_dir, env)

        all_report_dirs: List[Path] = []

        # 4. CSynthesis — one vitis_hls invocation per kernel
        for kernel_cpp in kernel_cpps:
            kernel_name = kernel_cpp.stem
            tcl_script  = project_dir / f'{kernel_name}_csynth.tcl'
            generate_csynth_tcl(
                project_dir, kernel_cpp, tcl_script,
                part, _TARGET_CLOCK_NS, cflags,
            )

            ret, out = _run(
                ['vitis_hls', '-f', str(tcl_script)],
                f"CSynthesis {kernel_name}",
            )
            if ret != 0:
                raise RuntimeError(
                    f"vitis_hls failed for {kernel_name}:\n" + '\n'.join(out[-20:])
                )

            rpt_dir = project_dir / f'{kernel_name}_csynth' / 'solution' / 'syn' / 'report'
            if rpt_dir.exists():
                all_report_dirs.append(rpt_dir)
            else:
                print(f"[{timestamp()}] [Thread {thread_id}] [{label}] "
                      f"Warning: report dir not found: {rpt_dir}")

        # 5. Parse csynth reports
        metrics = _parse_csynth_reports(all_report_dirs, thread_id, label=label)

        # 5a. Resource overflow check — skip additional stages if any resource
        #     exceeds 100% utilisation.  The design cannot be placed on the FPGA
        #     so no further timing information is obtainable or useful.
        #     synthesis_success is still True (csynth completed); _calculate_reward
        #     will assign 0.0 to the overflowing resource objectives automatically.
        
        from fpga_specs import calculate_slr_utilization, U280_SPEC
        _util = calculate_slr_utilization(metrics, U280_SPEC)
        _overflow = {r: u for r, u in _util.items() if r in ('bram', 'dsp', 'lut', 'ff') and u > 1.0}
        if _overflow:
            _over_str = '  '.join(f"{r}={u*100:.1f}%" for r, u in sorted(_overflow.items()))
            print(f"[{timestamp()}] [Thread {thread_id}] [{label}] "
                  f"Resource overflow: {_over_str}")
            metrics['synthesis_success']  = True
            metrics['resource_overflow']  = True
            metrics['synthesis_time']     = time.time() - start_time
            return metrics

        metrics['synthesis_success'] = True
        metrics['synthesis_time']    = time.time() - start_time
        return metrics

    except subprocess.TimeoutExpired:
        return {
            'synthesis_success': False,
            'synthesis_time': timeout,
            'error_message': 'vitis_hls timeout',
            'frequency': 0, 'latency': 0,
        }
    except Exception as e:
        return {
            'synthesis_success': False,
            'synthesis_time': time.time() - start_time if 'start_time' in locals() else 0,
            'error_message': str(e),
            'frequency': 0, 'latency': 0,
        }
